"""Pydantic models for media metadata."""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel

from src.models.common import ListResponse


class MediaCreate(BaseModel):
    """Input schema for creating a media record.

    Attributes:
        filename: Unique stored filename (generated by the image/video module).
        mime_type: MIME content type of the file (e.g. ``image/jpeg``).
        size: File size in bytes.
        title: Optional human-readable title for the media item.
        plant_id: Optional associated plant id.
        tag_id: Optional associated tag id.
        species_id: Optional associated species id.
    """

    filename: str
    mime_type: str
    size: int
    title: Optional[str] = None
    plant_id: int | None = None
    tag_id: int | None = None
    species_id: int | None = None


class Media(MediaCreate):
    """Full media record as stored in the database.

    Attributes:
        id: Auto-assigned primary key.
        uploaded_at: ISO-8601 UTC timestamp of when the file was saved.
    """

    id: int
    uploaded_at: datetime
    file_path: str | None = None

    model_config = {"from_attributes": True}


class MediaListItem(BaseModel):
    """Lightweight media representation for list endpoints."""

    id: int
    filename: str
    title: str | None = None
    mime_type: str
    plant_id: int | None = None
    tag_id: int | None = None
    species_id: int | None = None
    file_path: str | None = None


class MediaListResponse(ListResponse[MediaListItem]):
    """List envelope for media list endpoints."""
